language: java

services:
  - xvfb

jdk:
  - openjdk11

before_install:
  - sudo apt-get install -y openjfx libopenjfx-java

after_success:
  - mvn clean test jacoco:report coveralls:report
